// Generated automatically by nearley, version 2.13.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

const moo = require('./moo/moo')
const ast = require('./ast')

const caseInsensitiveKeywords = map => {
  const transform = moo.keywords(map)
  return text => transform(text.toLowerCase())
}

let lexer = moo.compile({
    comment:    { match: /[ \t]*(?:REM(?![\w!#$%])|').*?(?:\r?\n[ \t]*|$)/, lineBreaks: true },
    NL:         { match: /(?:[ \t]*\r?\n[ \t]*)+/, lineBreaks: true },
    ws:         { match: /[ \t]+/ },
    IDENTIFIER: { match: /[a-zA-Z_][\w]*[$%!#]?/, value: x=>x.toLowerCase(),
        type: caseInsensitiveKeywords({
            constant: ['true', 'false', 'invalid'],
            reserved: ['end','if','else','elseif','exit','not','and','or','return','function','sub','print']
        })
    },
    number:     /\d+%|\d*\.?\d+(?:[edED][+-]?\d+)?[!#&]?|&h[0-9ABCDEFabcdef]+/,
    string:     /"(?:[^"\n\r]*(?:"")*)*"/,
    op:         /<>|<=|>=|<<|>>|\+=|-=|\*=|\/=|\\=|<<=|>>=/,
    othr:       /./
})
const u = d => d[0][0]
const l = (s) => (d) => s
const flat = d => {
    let a = []
    for (const e of d) {
        if (Array.isArray(e)) {
            a.push(...e)
        } else {
            a.push(e)
        }
    }
    return a
}

var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "program$ebnf$1", "symbols": ["statement_separators"], "postprocess": id},
    {"name": "program$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "program", "symbols": ["libs", "functions", "program$ebnf$1"], "postprocess": ast.program},
    {"name": "libs", "symbols": []},
    {"name": "libs$ebnf$1", "symbols": ["statement_separators"], "postprocess": id},
    {"name": "libs$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "libs$ebnf$2", "symbols": []},
    {"name": "libs$ebnf$2$subexpression$1", "symbols": ["statement_separators", "library"]},
    {"name": "libs$ebnf$2", "symbols": ["libs$ebnf$2", "libs$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "libs", "symbols": ["libs$ebnf$1", "library", "libs$ebnf$2"], "postprocess": ast.libs},
    {"name": "library", "symbols": [{"literal":"library"}, "__", "string"], "postprocess": ast.lib},
    {"name": "functions$ebnf$1", "symbols": []},
    {"name": "functions$ebnf$1$subexpression$1$ebnf$1", "symbols": ["statement_separators"], "postprocess": id},
    {"name": "functions$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "functions$ebnf$1$subexpression$1", "symbols": ["functions$ebnf$1$subexpression$1$ebnf$1", "function"]},
    {"name": "functions$ebnf$1", "symbols": ["functions$ebnf$1", "functions$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "functions", "symbols": ["functions$ebnf$1"], "postprocess": ast.functions},
    {"name": "function", "symbols": ["func"], "postprocess": id},
    {"name": "function", "symbols": ["sub"], "postprocess": id},
    {"name": "func$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"as"}, "__", "rtype"]},
    {"name": "func$ebnf$1", "symbols": ["func$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "func$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "func", "symbols": [{"literal":"function"}, "__", "NAME", "_", {"literal":"("}, "params", {"literal":")"}, "func$ebnf$1", "statement_list", "end_function"], "postprocess": ast.func},
    {"name": "end_function", "symbols": [{"literal":"end"}, "__", {"literal":"function"}]},
    {"name": "end_function", "symbols": [{"literal":"endfunction"}]},
    {"name": "sub$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"as"}, "__", "rtype"]},
    {"name": "sub$ebnf$1", "symbols": ["sub$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "sub$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sub$subexpression$1", "symbols": [{"literal":"end"}, "__", {"literal":"sub"}]},
    {"name": "sub$subexpression$1", "symbols": [{"literal":"endsub"}]},
    {"name": "sub", "symbols": [{"literal":"sub"}, "__", "NAME", "_", {"literal":"("}, "params", {"literal":")"}, "sub$ebnf$1", "statement_list", "sub$subexpression$1"], "postprocess": ast.func},
    {"name": "anonymous_function$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"as"}, "__", "rtype"]},
    {"name": "anonymous_function$ebnf$1", "symbols": ["anonymous_function$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "anonymous_function$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "anonymous_function", "symbols": [{"literal":"function"}, "_", {"literal":"("}, "params", {"literal":")"}, "anonymous_function$ebnf$1", "statement_list", "end_function"], "postprocess": ast.afunc},
    {"name": "anonymous_function$ebnf$2$subexpression$1", "symbols": ["_", {"literal":"as"}, "__", "rtype"]},
    {"name": "anonymous_function$ebnf$2", "symbols": ["anonymous_function$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "anonymous_function$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "anonymous_function$subexpression$1", "symbols": [{"literal":"end"}, "_", {"literal":"sub"}]},
    {"name": "anonymous_function$subexpression$1", "symbols": [{"literal":"endsub"}]},
    {"name": "anonymous_function", "symbols": [{"literal":"sub"}, "_", {"literal":"("}, "params", {"literal":")"}, "anonymous_function$ebnf$2", "statement_list", "anonymous_function$subexpression$1"], "postprocess": ast.afunc},
    {"name": "params$ebnf$1", "symbols": []},
    {"name": "params$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", "param"]},
    {"name": "params$ebnf$1", "symbols": ["params$ebnf$1", "params$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "params", "symbols": ["_", "param", "params$ebnf$1", "_"], "postprocess": ast.params},
    {"name": "params", "symbols": ["_"], "postprocess": ast.params},
    {"name": "param$ebnf$1", "symbols": ["param_default"], "postprocess": id},
    {"name": "param$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "param$ebnf$2", "symbols": ["param_type"], "postprocess": id},
    {"name": "param$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "param", "symbols": ["IDENTIFIER", "param$ebnf$1", "param$ebnf$2"], "postprocess": ast.param},
    {"name": "param_default", "symbols": ["_", {"literal":"="}, "_", "rval"]},
    {"name": "param_type", "symbols": ["_", {"literal":"as"}, "__", "ptype"]},
    {"name": "ptype", "symbols": ["type"], "postprocess": u},
    {"name": "rtype", "symbols": ["type"], "postprocess": u},
    {"name": "rtype", "symbols": [{"literal":"void"}], "postprocess": id},
    {"name": "type", "symbols": [{"literal":"boolean"}]},
    {"name": "type", "symbols": [{"literal":"integer"}]},
    {"name": "type", "symbols": [{"literal":"longinteger"}]},
    {"name": "type", "symbols": [{"literal":"float"}]},
    {"name": "type", "symbols": [{"literal":"double"}]},
    {"name": "type", "symbols": [{"literal":"string"}]},
    {"name": "type", "symbols": [{"literal":"object"}]},
    {"name": "type", "symbols": [{"literal":"dynamic"}]},
    {"name": "type", "symbols": [{"literal":"function"}]},
    {"name": "statement_list$ebnf$1", "symbols": []},
    {"name": "statement_list$ebnf$1$subexpression$1", "symbols": ["statement_separators", "statement"]},
    {"name": "statement_list$ebnf$1", "symbols": ["statement_list$ebnf$1", "statement_list$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "statement_list", "symbols": ["statement_list$ebnf$1", "statement_separators"], "postprocess": ast.statements},
    {"name": "statement_separators$ebnf$1", "symbols": ["statement_separator"]},
    {"name": "statement_separators$ebnf$1", "symbols": ["statement_separators$ebnf$1", "statement_separator"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "statement_separators", "symbols": ["statement_separators$ebnf$1", "_"], "postprocess": ast.statement_separators},
    {"name": "statement_separator", "symbols": ["NL"]},
    {"name": "statement_separator", "symbols": ["_", {"literal":":"}]},
    {"name": "statement", "symbols": ["if_statement"]},
    {"name": "statement", "symbols": ["dim_statement"]},
    {"name": "statement", "symbols": ["for_loop"]},
    {"name": "statement", "symbols": ["for_each"]},
    {"name": "statement", "symbols": ["while_loop"]},
    {"name": "statement", "symbols": ["exit_loop"]},
    {"name": "statement", "symbols": ["return_statement"]},
    {"name": "statement", "symbols": ["stop_statement"]},
    {"name": "statement", "symbols": ["end_statement"]},
    {"name": "statement", "symbols": ["assign_statement"]},
    {"name": "statement", "symbols": ["call_statement"]},
    {"name": "statement", "symbols": ["print_statement"]},
    {"name": "oneline_statement", "symbols": ["oneline_if"]},
    {"name": "oneline_statement", "symbols": ["return_statement"]},
    {"name": "oneline_statement", "symbols": ["stop_statement"]},
    {"name": "oneline_statement", "symbols": ["end_statement"]},
    {"name": "oneline_statement", "symbols": ["exit_loop"]},
    {"name": "oneline_statement", "symbols": ["assign_statement"]},
    {"name": "oneline_statement", "symbols": ["call_statement"]},
    {"name": "oneline_statement", "symbols": ["print_statement"]},
    {"name": "if_statement$ebnf$1", "symbols": []},
    {"name": "if_statement$ebnf$1", "symbols": ["if_statement$ebnf$1", "else_if"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "if_statement$ebnf$2$subexpression$1", "symbols": [{"literal":"else"}, "statement_list_or_space"]},
    {"name": "if_statement$ebnf$2", "symbols": ["if_statement$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "if_statement$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "if_statement", "symbols": [{"literal":"if"}, "if_body", "if_statement$ebnf$1", "if_statement$ebnf$2", "endif"], "postprocess": ast.if},
    {"name": "if_statement", "symbols": ["oneline_if"], "postprocess": id},
    {"name": "else_if", "symbols": ["elseif", "if_body"]},
    {"name": "if_body$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"then"}]},
    {"name": "if_body$ebnf$1", "symbols": ["if_body$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "if_body$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "if_body", "symbols": ["_", "EXPR", "if_body$ebnf$1", "statement_list"]},
    {"name": "elseif", "symbols": [{"literal":"else"}, "__", {"literal":"if"}]},
    {"name": "elseif", "symbols": [{"literal":"elseif"}]},
    {"name": "endif", "symbols": [{"literal":"end"}, "__", {"literal":"if"}]},
    {"name": "endif", "symbols": [{"literal":"endif"}]},
    {"name": "oneline_if$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"then"}]},
    {"name": "oneline_if$ebnf$1", "symbols": ["oneline_if$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "oneline_if$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "oneline_if$ebnf$2$subexpression$1", "symbols": ["_", {"literal":"else"}, "__", "oneline_statement"]},
    {"name": "oneline_if$ebnf$2", "symbols": ["oneline_if$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "oneline_if$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "oneline_if", "symbols": [{"literal":"if"}, "_", "EXPR", "oneline_if$ebnf$1", "_", "oneline_statement", "oneline_if$ebnf$2"], "postprocess": ast.oneline_if},
    {"name": "statement_list_or_space", "symbols": ["statement_list"], "postprocess": id},
    {"name": "statement_list_or_space", "symbols": ["__"], "postprocess": id},
    {"name": "dim_statement", "symbols": [{"literal":"dim"}, "__", "IDENTIFIER", "_", {"literal":"["}, "_", "expression_list", "_", {"literal":"]"}], "postprocess": ast.dim},
    {"name": "expression_list$ebnf$1", "symbols": []},
    {"name": "expression_list$ebnf$1$subexpression$1", "symbols": ["EXPR", "_", {"literal":","}, "_"]},
    {"name": "expression_list$ebnf$1", "symbols": ["expression_list$ebnf$1", "expression_list$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "expression_list", "symbols": ["expression_list$ebnf$1", "EXPR"], "postprocess": ast.expr_list},
    {"name": "for_loop$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"step"}, "_", "EXPR"]},
    {"name": "for_loop$ebnf$1", "symbols": ["for_loop$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "for_loop$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "for_loop", "symbols": [{"literal":"for"}, "__", "IDENTIFIER", "_", {"literal":"="}, "_", "EXPR", "_", {"literal":"to"}, "_", "EXPR", "for_loop$ebnf$1", "statement_list", "end_for"], "postprocess": ast.for},
    {"name": "end_for", "symbols": [{"literal":"end"}, "__", {"literal":"for"}]},
    {"name": "end_for", "symbols": [{"literal":"endfor"}]},
    {"name": "end_for$ebnf$1$subexpression$1", "symbols": ["__", "IDENTIFIER"]},
    {"name": "end_for$ebnf$1", "symbols": ["end_for$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "end_for$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "end_for", "symbols": [{"literal":"next"}, "end_for$ebnf$1"]},
    {"name": "for_each$subexpression$1", "symbols": [{"literal":"for"}, "__", {"literal":"each"}]},
    {"name": "for_each$subexpression$1", "symbols": [{"literal":"foreach"}]},
    {"name": "for_each", "symbols": ["for_each$subexpression$1", "__", "IDENTIFIER", "__", {"literal":"in"}, "_", "rval", "statement_list", "end_for_each"], "postprocess": ast.foreach},
    {"name": "end_for_each", "symbols": [{"literal":"end"}, "__", {"literal":"for"}]},
    {"name": "end_for_each", "symbols": [{"literal":"endfor"}]},
    {"name": "end_for_each", "symbols": [{"literal":"next"}], "postprocess": id},
    {"name": "while_loop$subexpression$1", "symbols": [{"literal":"end"}, "__", {"literal":"while"}]},
    {"name": "while_loop$subexpression$1", "symbols": [{"literal":"endwhile"}]},
    {"name": "while_loop", "symbols": [{"literal":"while"}, "_", "EXPR", "statement_list", "while_loop$subexpression$1"], "postprocess": ast.while},
    {"name": "exit_loop", "symbols": [{"literal":"exit"}, "__", {"literal":"while"}], "postprocess": ast.exit},
    {"name": "exit_loop", "symbols": [{"literal":"exitwhile"}], "postprocess": ast.exit},
    {"name": "exit_loop", "symbols": [{"literal":"exit"}, "__", {"literal":"for"}], "postprocess": ast.exit},
    {"name": "return_statement$ebnf$1$subexpression$1", "symbols": ["_", "rval"]},
    {"name": "return_statement$ebnf$1", "symbols": ["return_statement$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "return_statement$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "return_statement", "symbols": [{"literal":"return"}, "return_statement$ebnf$1"], "postprocess": ast.return},
    {"name": "stop_statement", "symbols": [{"literal":"stop"}], "postprocess": ast.stop},
    {"name": "end_statement", "symbols": [{"literal":"end"}], "postprocess": ast.end},
    {"name": "goto_label", "symbols": ["IDENTIFIER", "_", {"literal":":"}]},
    {"name": "goto_statement", "symbols": [{"literal":"goto"}, "__", "IDENTIFIER"]},
    {"name": "print_statement", "symbols": ["print", "print_items"], "postprocess": ast.print},
    {"name": "print", "symbols": [{"literal":"print"}], "postprocess": id},
    {"name": "print", "symbols": [{"literal":"?"}], "postprocess": id},
    {"name": "print_items$ebnf$1", "symbols": []},
    {"name": "print_items$ebnf$1", "symbols": ["print_items$ebnf$1", "psep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "print_items", "symbols": ["print_items$ebnf$1"], "postprocess": id},
    {"name": "print_items$ebnf$2", "symbols": []},
    {"name": "print_items$ebnf$2", "symbols": ["print_items$ebnf$2", "psep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "print_items$ebnf$3", "symbols": []},
    {"name": "print_items$ebnf$3$subexpression$1", "symbols": ["_", "PEXPR"]},
    {"name": "print_items$ebnf$3$subexpression$1", "symbols": ["pxsp", "EXPR"]},
    {"name": "print_items$ebnf$3", "symbols": ["print_items$ebnf$3", "print_items$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "print_items$ebnf$4$subexpression$1$ebnf$1", "symbols": []},
    {"name": "print_items$ebnf$4$subexpression$1$ebnf$1", "symbols": ["print_items$ebnf$4$subexpression$1$ebnf$1", "psep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "print_items$ebnf$4$subexpression$1", "symbols": ["print_items$ebnf$4$subexpression$1$ebnf$1", "ppp"]},
    {"name": "print_items$ebnf$4", "symbols": ["print_items$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "print_items$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "print_items", "symbols": ["print_items$ebnf$2", "EXPR", "print_items$ebnf$3", "print_items$ebnf$4"], "postprocess": ast.print_items},
    {"name": "psep", "symbols": [{"literal":";"}], "postprocess": id},
    {"name": "psep", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "psep", "symbols": ["__"], "postprocess": id},
    {"name": "ppp", "symbols": [{"literal":";"}], "postprocess": id},
    {"name": "ppp", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "pxsp$ebnf$1", "symbols": []},
    {"name": "pxsp$ebnf$1", "symbols": ["pxsp$ebnf$1", "psep"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "pxsp", "symbols": ["_", "ppp", "pxsp$ebnf$1"], "postprocess": flat},
    {"name": "call_statement$ebnf$1", "symbols": []},
    {"name": "call_statement$ebnf$1", "symbols": ["call_statement$ebnf$1", "access_or_call"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "call_statement", "symbols": ["IDENTIFIER", "call_statement$ebnf$1", "call"], "postprocess": ast.lval},
    {"name": "assign_statement", "symbols": ["lval", "_", "assign_op", "_", "rval"], "postprocess": ast.assign},
    {"name": "assign_statement", "symbols": ["lval", "_", "incdec"], "postprocess": ast.incdec},
    {"name": "assign_op", "symbols": [{"literal":"="}]},
    {"name": "assign_op", "symbols": [{"literal":"+="}]},
    {"name": "assign_op", "symbols": [{"literal":"-="}]},
    {"name": "assign_op", "symbols": [{"literal":"*="}]},
    {"name": "assign_op", "symbols": [{"literal":"/="}]},
    {"name": "assign_op", "symbols": [{"literal":"\\="}]},
    {"name": "assign_op", "symbols": [{"literal":"<<="}]},
    {"name": "assign_op", "symbols": [{"literal":">>="}]},
    {"name": "incdec", "symbols": [{"literal":"+"}, {"literal":"+"}], "postprocess": l('++')},
    {"name": "incdec", "symbols": [{"literal":"-"}, {"literal":"-"}], "postprocess": l('--')},
    {"name": "lval", "symbols": ["IDENTIFIER"], "postprocess": id},
    {"name": "lval$ebnf$1", "symbols": []},
    {"name": "lval$ebnf$1", "symbols": ["lval$ebnf$1", "access_or_call"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lval", "symbols": ["IDENTIFIER", "lval$ebnf$1", "access"], "postprocess": ast.lval},
    {"name": "access", "symbols": ["_", {"literal":"."}, "_", "PROP_NAME"], "postprocess": ast.prop},
    {"name": "access$ebnf$1", "symbols": []},
    {"name": "access$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", "EXPR"]},
    {"name": "access$ebnf$1", "symbols": ["access$ebnf$1", "access$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "access", "symbols": ["_", {"literal":"["}, "_", "EXPR", "access$ebnf$1", "_", {"literal":"]"}], "postprocess": ast.index},
    {"name": "call$ebnf$1", "symbols": []},
    {"name": "call$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", "rval"]},
    {"name": "call$ebnf$1", "symbols": ["call$ebnf$1", "call$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "call", "symbols": ["_", {"literal":"("}, "_", "rval", "call$ebnf$1", "_", {"literal":")"}], "postprocess": ast.call},
    {"name": "call", "symbols": ["_", {"literal":"("}, "_", {"literal":")"}], "postprocess": ast.call},
    {"name": "xmlattr", "symbols": ["_", {"literal":"@"}, "_", "ATTR_NAME"], "postprocess": ast.xmlattr},
    {"name": "PROP_NAME", "symbols": ["IDENTIFIER"], "postprocess": ast.name},
    {"name": "PROP_NAME", "symbols": ["RESERVED"], "postprocess": ast.name},
    {"name": "PROP_NAME", "symbols": ["constant"], "postprocess": ast.name},
    {"name": "PROP_NAME", "symbols": ["string"], "postprocess": ast.name},
    {"name": "ATTR_NAME", "symbols": ["IDENTIFIER"], "postprocess": ast.name},
    {"name": "ATTR_NAME", "symbols": ["RESERVED"], "postprocess": ast.name},
    {"name": "access_or_call", "symbols": ["access"], "postprocess": id},
    {"name": "access_or_call", "symbols": ["call"], "postprocess": id},
    {"name": "picx", "symbols": ["access"], "postprocess": id},
    {"name": "picx", "symbols": ["call"], "postprocess": id},
    {"name": "picx", "symbols": ["xmlattr"], "postprocess": id},
    {"name": "rval", "symbols": ["EXPR"], "postprocess": id},
    {"name": "rval", "symbols": ["object_literal"], "postprocess": id},
    {"name": "rval", "symbols": ["array_literal"], "postprocess": id},
    {"name": "rval", "symbols": ["anonymous_function"], "postprocess": id},
    {"name": "object_literal$ebnf$1", "symbols": []},
    {"name": "object_literal$ebnf$1$subexpression$1", "symbols": ["prop", "lisep"]},
    {"name": "object_literal$ebnf$1", "symbols": ["object_literal$ebnf$1", "object_literal$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "object_literal$subexpression$1", "symbols": ["_"]},
    {"name": "object_literal$subexpression$1", "symbols": ["lisep"]},
    {"name": "object_literal", "symbols": [{"literal":"{"}, "_NL", "object_literal$ebnf$1", "prop", "object_literal$subexpression$1", {"literal":"}"}], "postprocess": ast.object},
    {"name": "object_literal", "symbols": [{"literal":"{"}, "_NL", {"literal":"}"}], "postprocess": ast.object},
    {"name": "array_literal$ebnf$1", "symbols": []},
    {"name": "array_literal$ebnf$1$subexpression$1", "symbols": ["rval", "lisep"]},
    {"name": "array_literal$ebnf$1", "symbols": ["array_literal$ebnf$1", "array_literal$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "array_literal$subexpression$1", "symbols": ["_"]},
    {"name": "array_literal$subexpression$1", "symbols": ["lisep"]},
    {"name": "array_literal", "symbols": [{"literal":"["}, "_NL", "array_literal$ebnf$1", "rval", "array_literal$subexpression$1", {"literal":"]"}], "postprocess": ast.array},
    {"name": "array_literal", "symbols": [{"literal":"["}, "_NL", {"literal":"]"}], "postprocess": ast.array},
    {"name": "prop", "symbols": ["PROP_NAME", "_", {"literal":":"}, "_", "rval"], "postprocess": ast.propdef},
    {"name": "lisep", "symbols": ["_", {"literal":","}, "_NL"]},
    {"name": "lisep$ebnf$1", "symbols": ["NL"]},
    {"name": "lisep$ebnf$1", "symbols": ["lisep$ebnf$1", "NL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lisep", "symbols": ["lisep$ebnf$1"]},
    {"name": "val", "symbols": ["IDENTIFIER"], "postprocess": id},
    {"name": "val", "symbols": ["number"], "postprocess": id},
    {"name": "val", "symbols": ["string"], "postprocess": id},
    {"name": "val", "symbols": ["constant"], "postprocess": id},
    {"name": "EXPR", "symbols": ["O"], "postprocess": ast.expr},
    {"name": "P", "symbols": [{"literal":"("}, "_", "O", "_", {"literal":")"}], "postprocess": ast.parenthesis},
    {"name": "P", "symbols": ["val"], "postprocess": id},
    {"name": "AOP$ebnf$1", "symbols": ["picx"]},
    {"name": "AOP$ebnf$1", "symbols": ["AOP$ebnf$1", "picx"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "AOP", "symbols": ["P", "AOP$ebnf$1"], "postprocess": ast.access},
    {"name": "AOP", "symbols": ["P"], "postprocess": id},
    {"name": "U$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "U$subexpression$1", "symbols": [{"literal":"+"}]},
    {"name": "U", "symbols": ["U$subexpression$1", "_", "U"], "postprocess": ast.uop},
    {"name": "U", "symbols": ["AOP"], "postprocess": id},
    {"name": "E", "symbols": ["U", "_", {"literal":"^"}, "_", "E"], "postprocess": ast.bop},
    {"name": "E", "symbols": ["U"], "postprocess": id},
    {"name": "M", "symbols": ["M", "_", "mul_op", "_", "E"], "postprocess": ast.bop},
    {"name": "M", "symbols": ["E"], "postprocess": id},
    {"name": "A", "symbols": ["A", "_", "add_op", "_", "M"], "postprocess": ast.bop},
    {"name": "A", "symbols": ["M"], "postprocess": id},
    {"name": "S", "symbols": ["S", "_", "shft_op", "_", "A"], "postprocess": ast.bop},
    {"name": "S", "symbols": ["A"], "postprocess": id},
    {"name": "C", "symbols": ["C", "_", "comp_op", "_", "S"], "postprocess": ast.bop},
    {"name": "C", "symbols": ["S"], "postprocess": id},
    {"name": "N", "symbols": [{"literal":"not"}, "_", "N"], "postprocess": ast.uop},
    {"name": "N", "symbols": ["C"], "postprocess": id},
    {"name": "D", "symbols": ["D", "_", {"literal":"and"}, "_", "N"], "postprocess": ast.bop},
    {"name": "D", "symbols": ["N"], "postprocess": id},
    {"name": "O", "symbols": ["O", "_", {"literal":"or"}, "_", "D"], "postprocess": ast.bop},
    {"name": "O", "symbols": ["D"], "postprocess": id},
    {"name": "PEXPR", "symbols": ["PO"], "postprocess": ast.expr},
    {"name": "PAOP$ebnf$1", "symbols": ["picx"]},
    {"name": "PAOP$ebnf$1", "symbols": ["PAOP$ebnf$1", "picx"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "PAOP", "symbols": ["val", "PAOP$ebnf$1"], "postprocess": ast.access},
    {"name": "PAOP", "symbols": ["val"], "postprocess": id},
    {"name": "PE", "symbols": ["PAOP", "_", {"literal":"^"}, "_", "E"], "postprocess": ast.bop},
    {"name": "PE", "symbols": ["PAOP"], "postprocess": id},
    {"name": "PM", "symbols": ["PM", "_", "mul_op", "_", "E"], "postprocess": ast.bop},
    {"name": "PM", "symbols": ["PE"], "postprocess": id},
    {"name": "PA", "symbols": ["PA", "_", "add_op", "_", "M"], "postprocess": ast.bop},
    {"name": "PA", "symbols": ["PM"], "postprocess": id},
    {"name": "PS", "symbols": ["PS", "_", "shft_op", "_", "A"], "postprocess": ast.bop},
    {"name": "PS", "symbols": ["PA"], "postprocess": id},
    {"name": "PC", "symbols": ["PC", "_", "comp_op", "_", "S"], "postprocess": ast.bop},
    {"name": "PC", "symbols": ["PS"], "postprocess": id},
    {"name": "PN", "symbols": [{"literal":"not"}, "_", "N"], "postprocess": ast.uop},
    {"name": "PN", "symbols": ["PC"], "postprocess": id},
    {"name": "PD", "symbols": ["PD", "_", {"literal":"and"}, "_", "N"], "postprocess": ast.bop},
    {"name": "PD", "symbols": ["PN"], "postprocess": id},
    {"name": "PO", "symbols": ["PO", "_", {"literal":"or"}, "_", "D"], "postprocess": ast.bop},
    {"name": "PO", "symbols": ["PD"], "postprocess": id},
    {"name": "add_op", "symbols": [{"literal":"+"}]},
    {"name": "add_op", "symbols": [{"literal":"-"}]},
    {"name": "mul_op", "symbols": [{"literal":"*"}]},
    {"name": "mul_op", "symbols": [{"literal":"/"}]},
    {"name": "mul_op", "symbols": [{"literal":"\\"}]},
    {"name": "mul_op", "symbols": [{"literal":"mod"}]},
    {"name": "shft_op", "symbols": [{"literal":">>"}]},
    {"name": "shft_op", "symbols": [{"literal":"<<"}]},
    {"name": "comp_op", "symbols": [{"literal":"="}]},
    {"name": "comp_op", "symbols": [{"literal":"<>"}]},
    {"name": "comp_op", "symbols": [{"literal":"<"}]},
    {"name": "comp_op", "symbols": [{"literal":">"}]},
    {"name": "comp_op", "symbols": [{"literal":"<="}]},
    {"name": "comp_op", "symbols": [{"literal":">="}]},
    {"name": "_$ebnf$1", "symbols": [(lexer.has("ws") ? {type: "ws"} : ws)], "postprocess": id},
    {"name": "_$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": id},
    {"name": "__", "symbols": [(lexer.has("ws") ? {type: "ws"} : ws)], "postprocess": id},
    {"name": "comment", "symbols": [(lexer.has("comment") ? {type: "comment"} : comment)], "postprocess": ast.comment},
    {"name": "NAME", "symbols": [(lexer.has("IDENTIFIER") ? {type: "IDENTIFIER"} : IDENTIFIER)], "postprocess": ast.identifier},
    {"name": "IDENTIFIER", "symbols": [(lexer.has("IDENTIFIER") ? {type: "IDENTIFIER"} : IDENTIFIER)], "postprocess": ast.identifier},
    {"name": "RESERVED", "symbols": [(lexer.has("reserved") ? {type: "reserved"} : reserved)], "postprocess": ast.identifier},
    {"name": "number", "symbols": [(lexer.has("number") ? {type: "number"} : number)], "postprocess": ast.number},
    {"name": "string", "symbols": [(lexer.has("string") ? {type: "string"} : string)], "postprocess": ast.string},
    {"name": "constant", "symbols": [(lexer.has("constant") ? {type: "constant"} : constant)], "postprocess": ast.constant},
    {"name": "NL", "symbols": [(lexer.has("comment") ? {type: "comment"} : comment)], "postprocess": ast.comment},
    {"name": "NL", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": id},
    {"name": "_NL", "symbols": ["_"]},
    {"name": "_NL$ebnf$1", "symbols": ["NL"]},
    {"name": "_NL$ebnf$1", "symbols": ["_NL$ebnf$1", "NL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_NL", "symbols": ["_NL$ebnf$1"]}
]
  , ParserStart: "program"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
